### ISSUE TITLE
installation of Docker doesn't worked

### ISSUE THREAD

**Issue by daggerok** [Ash258/scoop-Ash258#50]
Hello,

please, let me know if you know how can I fix that?

```cmd
coop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json

Unpacking files : vcruntime140.dll 100%
Installing components 100%
[15:35:53.518] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[15:35:53.861] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[15:35:54.158] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[15:35:56.283] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[15:35:56.330] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[15:35:56.346] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[15:35:56.346] [InstallWorkflow] Component CommunityInstaller.AutoStartAction failed
Exception type: System.UnauthorizedAccessException, Exception message: Attempted to perform an unauthorized operation., StackTrace:
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
[15:35:56.346] [InstallWorkflow] Installation failed
Exception type: System.UnauthorizedAccessException, Exception message: Attempted to perform an unauthorized operation., StackTrace:
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
[15:35:56.346] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[15:35:56.346] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[15:35:56.362] [InstallWorkflow] Rollbacking component CommunityInstaller.ServiceAction
[15:35:56.487] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[15:35:56.487] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[15:35:56.487] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
Removing files 0%0%
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CommunityInstaller.UnpackArtifactsStep.<UndoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<Rollback>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CommunityInstaller.ConsoleWizardUI.Start()
   at CommunityInstaller.Cmd.InstallHandler.Run(String[] args)
   at CommunityInstaller.Program.Main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at CommunityInstaller.UnpackArtifactsStep.<UndoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<Rollback>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()<---
error.
ERROR Exit code was -1!
Installation aborted. You might need to run 'scoop uninstall docker' before trying again.
```

Thanks!

**Comment by Ash258** [comment]
`System.UnauthorizedAccessException, Exception message: Attempted to perform an unauthorized operation.`

`sudo scoop install Docker`

**Comment by daggerok** [comment]
Hello @Ash258,

```powershell
PS H:\> sudo scoop install Docker
The Win32 internal error "The handle is invalid" 0x6 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
```

or by `sudo` you mean open powershell console with `rus as administrator`?

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/sudo.json

**Comment by daggerok** [comment]
Thanks for your help,
I was able to exec that `scoop install Docker`, but it's not what I need, It's not Docker for Windows, seems like this one is intended to be used together with `docker-toolbox`

**Comment by Ash258** [comment]
...

Should I have to do everything instead of you??
`sudo scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/master/bucket/docker.json`

**Comment by daggerok** [comment]
of course no, I did same and result is same as it was in a first  message of that discussion:

```
...
Unpacking files : resources/wsl/lifecycle-controller-api.exe 100%
Unpacking files : vccorlib140.dll 100%
Unpacking files : vcruntime140.dll 100%
Installing components 100%
[16:55:13.703] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[16:55:13.812] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[16:55:13.906] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[16:55:15.016] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[16:55:15.078] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[16:55:15.078] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[16:55:15.094] [InstallWorkflow] Component CommunityInstaller.AutoStartAction failed
Exception type: System.UnauthorizedAccessException, Exception message: Attempted to perform an unauthorized operation., StackTrace:
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
[16:55:15.094] [InstallWorkflow] Installation failed
Exception type: System.UnauthorizedAccessException, Exception message: Attempted to perform an unauthorized operation., StackTrace:
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at CommunityInstaller.AutoStartAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
[16:55:15.094] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[16:55:15.094] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[16:55:15.094] [InstallWorkflow] Rollbacking component CommunityInstaller.ServiceAction
[16:55:15.219] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[16:55:15.219] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[16:55:15.219] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
Removing files 0%0%
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CommunityInstaller.UnpackArtifactsStep.<UndoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<Rollback>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CommunityInstaller.ConsoleWizardUI.Start()
   at CommunityInstaller.Cmd.InstallHandler.Run(String[] args)
   at CommunityInstaller.Program.Main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at CommunityInstaller.UnpackArtifactsStep.<UndoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<Rollback>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()<---
error.
ERROR Exit code was -1!
Installation aborted. You might need to run 'scoop uninstall docker' before trying again.
```

**Comment by Ash258** [comment]
https://github.com/docker/for-win/issues/1184#issuecomment-473370979
